/* Astria Course — Build Dashboard
   Renders site/manifest.json into a browsable, debuggable course view. */

const STATUS_LABEL = { built: "Built", failed: "Render failed", unchanged: "Unchanged" };

function esc(s) {
  return String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function fmtDur(sec) {
  if (!sec || sec <= 0) return "—";
  const s = Math.round(sec);
  return s >= 60 ? `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}` : `${s}s`;
}

function videoBlock(seg) {
  if (seg.status === "failed" || !seg.videoUrl) {
    return `<div class="seg-video"><div class="placeholder">No video — this segment did not render.<br/>Check the build log.</div></div>`;
  }
  return `<div class="seg-video"><video controls preload="none" playsinline src="${esc(seg.videoUrl)}"></video></div>`;
}

function inputBlock(label, url, kind) {
  if (!url) return `<div class="input"><div class="k">${esc(label)}</div><div class="missing">— not present</div></div>`;
  const media =
    kind === "audio"
      ? `<audio controls preload="none" src="${esc(url)}"></audio>`
      : `<video controls preload="none" playsinline src="${esc(url)}"></video>`;
  return `<div class="input"><div class="k">${esc(label)}</div>${media}</div>`;
}

function segmentCard(seg) {
  const inputs = [
    inputBlock("Avatar / talking head", seg.inputs.avatar, "video"),
    inputBlock("Narration audio", seg.inputs.audio, "audio"),
    inputBlock("Screencast capture", seg.inputs.capture, "video"),
  ].join("");

  return `
    <div class="seg is-${seg.status}">
      ${videoBlock(seg)}
      <div class="seg-body">
        <div class="seg-titlerow">
          <h3>${esc(seg.title)}</h3>
          <span class="badge ${seg.status}">${STATUS_LABEL[seg.status] || seg.status}</span>
          <span class="tag">${esc(seg.visual)}</span>
          <span class="tag">${fmtDur(seg.duration)}</span>
          <span class="seg-id">${esc(seg.id)}</span>
        </div>
        <div class="script-label">Script / on-screen text</div>
        <div class="script">${esc(seg.script)}</div>
        <details class="debug">
          <summary>Debug — input artifacts</summary>
          <div class="inputs">${inputs}</div>
        </details>
      </div>
    </div>`;
}

function moduleSection(p) {
  const fullDraft = p.fullDraftUrl
    ? `<details class="full-draft"><summary>Full-length cut (${fmtDur(p.duration)})</summary>
         <video controls preload="none" playsinline src="${esc(p.fullDraftUrl)}"></video></details>`
    : "";
  const stat = p.inBuild
    ? `${p.builtCount}/${p.segmentCount} segments · ${fmtDur(p.duration)}` +
      (p.failedCount ? ` · <span style="color:var(--bad)">${p.failedCount} failed</span>` : "")
    : "unchanged in this build — see the main site";

  return `
    <section class="module" id="mod-${esc(p.id)}">
      <div class="module-head">
        <h2>${esc(p.title)}</h2>
        <div class="stat">${stat}</div>
      </div>
      ${fullDraft}
      ${p.segments.map(segmentCard).join("")}
    </section>`;
}

function moduleDotStatus(p) {
  if (!p.inBuild) return "unchanged";
  if (p.failedCount) return "failed";
  return "built";
}

function render(m) {
  const modeChip = `<span class="chip mode ${m.buildMode}">${m.buildMode}</span>`;
  const chips = [
    modeChip,
    m.commit ? `<span class="chip">commit ${esc(m.commit)}</span>` : "",
    `<span class="chip">${new Date(m.generatedAt).toLocaleString()}</span>`,
  ].join("");

  const banner = m.pr
    ? `<div class="banner">Preview for <b>PR #${m.pr.number}</b> — ${esc(m.pr.title)}.
         ${m.buildMode === "draft"
           ? "DRAFT build: silent placeholder audio with burned-in captions. Comment <b>/render-paid</b> on the PR for a real render."
           : "PAID build: real narration, avatars and video."}</div>`
    : "";

  const totalSegs = m.projects.reduce((t, p) => t + p.segmentCount, 0);
  const totalFailed = m.projects.reduce((t, p) => t + p.failedCount, 0);
  const summary =
    `${m.projects.length} modules · ${totalSegs} segments` +
    (totalFailed ? ` · ${totalFailed} failed` : " · all rendered");

  const nav = m.projects
    .map(
      (p) =>
        `<a href="#mod-${esc(p.id)}"><span class="dot ${moduleDotStatus(p)}"></span>${esc(p.title)}</a>`,
    )
    .join("");

  document.getElementById("app").innerHTML = `
    <header class="top">
      <div class="top-inner">
        <div>
          <div class="eyebrow">Astria Course</div>
          <h1 class="title">Build Dashboard</h1>
        </div>
        <div class="meta-chips">${chips}</div>
      </div>
      ${banner}
    </header>
    <main>
      <div class="summary">${summary}</div>
      <nav class="modnav">${nav}</nav>
      ${m.projects.map(moduleSection).join("")}
    </main>
    <footer>
      Generated by <code>pipeline/build-dashboard.ts</code> from the rendered
      output of webinar-builder. Status: <b>Built</b> rendered this run ·
      <b>Render failed</b> needs attention · <b>Unchanged</b> not rebuilt in
      this PR (links to the live main site).
    </footer>`;
}

fetch("manifest.json", { cache: "no-store" })
  .then((r) => {
    if (!r.ok) throw new Error(`manifest.json ${r.status}`);
    return r.json();
  })
  .then(render)
  .catch((err) => {
    document.getElementById("app").innerHTML =
      `<div class="boot">Could not load manifest.json — ${esc(err.message)}</div>`;
  });
